# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2024-12-21T15:37:36+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class WebSocketResponse(BaseModel):
    image: Optional[str] = Field(None, description='Base64 encoded image')
