# generated by datamodel-codegen:
#   filename:  request.json
#   timestamp: 2024-12-22T09:44:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class WebSocketRequest(BaseModel):
    streamCamera: Optional[bool] = Field(
        None, description='Stream the camera to the client or not'
    )
    bucket: Optional[int] = Field(
        None, description='Move the given bucket under the belt'
    )
    clearBelt: Optional[bool] = Field(
        None, description='Request to clear the camera belt'
    )
    makeReferenceImage: Optional[bool] = Field(
        None,
        description='Make a new reference image, should be done when the belt is empty and is used to detect bricks in front of the camera.',
    )
