# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2025-01-26T10:16:49+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class WebSocketResponse(BaseModel):
    image: Optional[str] = Field(None, description='Base64 encoded image')
    referenceImage: Optional[str] = Field(
        None,
        description='Base64 encoded image of the empty belt that is used for detecting bricks',
    )
    thresholdImage: Optional[str] = Field(
        None,
        description='Base64 encoded image of the threshold values for detecting bricks',
    )
    prediction: Optional[str] = Field(None, description='Name of the predicted brick')
    prediction_url: Optional[str] = Field(
        None, description='URL to an image, if available, of the predicted brick'
    )
    machineRunning: bool = Field(
        ...,
        description='Indicate whether or not the machine is currently executing a command',
    )
