# generated by datamodel-codegen:
#   filename:  request.json
#   timestamp: 2025-01-26T11:01:55+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class BucketMapping(BaseModel):
    default: int = Field(
        ..., description='Default bucket number for unrecognized bricks'
    )
    mapping: Dict[str, List[str]] = Field(
        ..., description='Mapping of bucket numbers to brick types'
    )


class WebSocketRequest(BaseModel):
    streamCamera: Optional[bool] = Field(
        None, description='Stream the camera to the client or not'
    )
    bucket: Optional[int] = Field(
        None, description='Move the given bucket under the belt'
    )
    clearBelt: Optional[bool] = Field(
        None, description='Request to clear the camera belt'
    )
    makeReferenceImage: Optional[bool] = Field(
        None,
        description='Make a new reference image, should be done when the belt is empty and is used to detect bricks in front of the camera.',
    )
    nextBrick: Optional[bool] = Field(
        None, description='Move the next brick in front of the camera'
    )
    stop: Optional[bool] = Field(None, description='Stop the machine')
    start: Optional[bool] = Field(None, description='Start the machine')
    predictOne: Optional[bool] = Field(
        None, description='Move one brick in front of the camera and run the prediction'
    )
    bucketMapping: Optional[BucketMapping] = Field(
        None,
        description='Mapping of bucket numbers to brick types that should go in that bucket',
    )
