# generated by datamodel-codegen:
#   filename:  request.json
#   timestamp: 2024-12-21T09:32:24+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class WebSocketRequest(BaseModel):
    streamCamera: Optional[bool] = Field(
        None, description='Stream the camera to the client or not'
    )
