# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2024-12-22T09:44:39+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class WebSocketResponse(BaseModel):
    image: Optional[str] = Field(None, description='Base64 encoded image')
    referenceImage: Optional[str] = Field(
        None,
        description='Base64 encoded image of the empty belt that is used for detecting bricks',
    )
