services:
  lego-sorter-service:
    build:
      context: ..
      dockerfile: ./pc_serving/Dockerfile
    volumes:
      - ../data/new:/new_pictures
    ports:
      - "8000:8000"
    deploy:
      # https://docs.docker.com/compose/gpu-support/
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]