services:
  tensorflow-jupyter:
    build: .
#    user: "1000:1000"
    ports:
      - "5000:5000"
    deploy:
      # https://docs.docker.com/compose/gpu-support/
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]